# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g-d7jvGDQKt1anNzrcS-mEEf_7Yi8Hoz

IMPORT ALL THE NECESSARY LIBRARY
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

"""Load the dataset"""

df=pd.read_csv("epl_final.csv")

"""it is represent the 5 top column"""

df.head()

"""it is represent the 5 lower data"""

df.tail()

"""data information"""

df.shape

"""## it is represent the how many columns and how many rows are there

## rows= 9380
# columns=22

"""

df.info()

"""In this data set 16(interge value) and 6(object) columns are there"""

df.isnull().sum()

"""in this data set there are no any null value are there"""

df.describe()

df.duplicated().sum()

"""in this dataset no. any duplicate value are there"""



"""Jump to the  EDA part"""

df.columns

"""it is given the column name"""

plt.figure(figsize=(6,4))
df['FullTimeResult'].value_counts().plot(kind='bar', color=['skyblue', 'orange', 'green'])
plt.title("Full Time Match Outcomes")
plt.xlabel("Result (H = Home Win, D = Draw, A = Away Win)")
plt.ylabel("Match Count")
plt.show()

"""this is comparision Between HalfTime result and Full Time result"""

plt.figure(figsize=(10,4))
plt.subplot(1,2,1)
df['HalfTimeResult'].value_counts().plot(kind='bar', title='Half Time Results', color='purple')

plt.subplot(1,2,2)
df['FullTimeResult'].value_counts().plot(kind='bar', title='Full Time Results', color='teal')
plt.show()

numeric_cols = df.select_dtypes(include=['int64', 'float64'])
plt.figure(figsize=(10,8))
sns.heatmap(numeric_cols.corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title("Correlation Heatmap")
plt.show()

"""inseght:

High correlation (e.g., between ShotsOnTarget and Goals) means features are strongly related.
Helps decide which columns are most predictive.

Relationship Between Key Metrics
"""

sns.scatterplot(x='HomeShots', y='FullTimeHomeGoals', data=df, alpha=0.6)
plt.title("Home Shots vs Home Goals")
plt.show()

"""Insight:

Positive trend → more shots = more goals.
"""

sns.scatterplot(x='AwayShots', y='FullTimeAwayGoals', data=df, alpha=0.6, color='orange')
plt.title("Away Shots vs Away Goals")
plt.show()

discipline = df[['HomeFouls', 'AwayFouls', 'HomeYellowCards', 'AwayYellowCards', 'HomeRedCards', 'AwayRedCards']]
discipline.describe()

"""Insight:

“When there are too many fouls and yellow/red cards, it negatively affects the overall performance.”

You can visualize fouls vs result too.
"""

df['MatchDate'] = pd.to_datetime(df['MatchDate'])
df.groupby(df['MatchDate'].dt.year)[['FullTimeHomeGoals','FullTimeAwayGoals']].mean().plot(title='Average Goals per Year')

# Percentage-wise distribution of match results
ftr_percent = (df['FullTimeResult'].value_counts(normalize=True) * 100).round(2)

# Print result
print(ftr_percent)

# Graph banana ho to:
ftr_percent.plot(kind='pie', title='Distribution of Full Time Result (in %)', color=['skyblue', 'lightgreen', 'salmon'])
plt.ylabel('Percentage (%)')
plt.show()

"""45.83% MATCH ARE WINNING THE HOME TEAM

29.51% MATCH ARE WINNING THE AWAY TEAM

24.66% MATCH ARE DROW
"""

import matplotlib.pyplot as plt
import pandas as pd

# Group by HomeTeam and AwayTeam
home_goals = df.groupby('HomeTeam')['FullTimeHomeGoals'].mean()
away_goals = df.groupby('AwayTeam')['FullTimeAwayGoals'].mean()

# Combine into a DataFrame
avg_goals = pd.DataFrame({'Home Goals': home_goals, 'Away Goals': away_goals})

# Plot
avg_goals.plot(kind='bar', figsize=(12,6), color=['blue', 'red'])
plt.title('Average Goals by Team (Home vs Away)', fontsize=14)
plt.ylabel('Average Goals', fontsize=12)
plt.xlabel('Away Teams', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.show()

"""Blue Bars (Home Goals): Har team ne home matches me average kitne goals score kiye dikhata hai.

Red Bars (Away Goals): Har team ne away matches me average kitne goals score kiye dikhata hai.
"""

import pandas as pd
import matplotlib.pyplot as plt

# Read the dataset
df = pd.read_csv("epl_final.csv")

# Assuming your columns are named 'Season', 'FTHG' (home goals), and 'FTAG' (away goals)
df['Total_Goals'] = df['FullTimeHomeGoals'] + df['FullTimeAwayGoals']

# Group by season and sum total goals
goals_per_season = df.groupby('Season')['Total_Goals'].sum().reset_index()

# Plot the bar chart
plt.figure(figsize=(10,6))
plt.bar(goals_per_season['Season'], goals_per_season['Total_Goals'], color='red')
plt.title('Total Goals per Season', fontsize=14)
plt.xlabel('Season', fontsize=12)
plt.ylabel('Goals', fontsize=12)
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Numeric features to compare
numeric_cols = ['FullTimeHomeGoals', 'FullTimeAwayGoals']

# Plot
plt.figure(figsize=(14,8))
sns.boxplot(x='FullTimeResult', y='value', hue='variable',
            data=pd.melt(df, id_vars='FullTimeResult', value_vars=numeric_cols))
plt.title('Distribution of Key Features by Match Result (H, D, A)', fontsize=16)
plt.xlabel('Full Time Result (FullTimeResult)', fontsize=12)
plt.ylabel('Values', fontsize=12)
plt.show()





"""Feature Engineering"""

rename_map = {
    'HomeShots': 'HS',
    'AwayShots': 'AS',
    'HomeShotsOnTarget': 'HST',
    'AwayShotsOnTarget': 'AST',
    'HomeFouls': 'HF',
    'AwayFouls': 'AF',
    'HomeYellowCards': 'HY',
    'AwayYellowCards': 'AY',
    'HomeRedCards': 'HR',
    'AwayRedCards': 'AR'
}
df.rename(columns=rename_map, inplace=True)

"""Rename Columns for Consistency"""



"""Encode Teams and Result

import LabelEncoder
"""

from sklearn.preprocessing import LabelEncoder

team_encoder = LabelEncoder()
all_teams = pd.concat([df['HomeTeam'], df['AwayTeam']]).dropna().unique()
team_encoder.fit(all_teams)

df['HomeTeam_enc'] = team_encoder.transform(df['HomeTeam'])

df['AwayTeam_enc'] = team_encoder.transform(df['AwayTeam'])

result_encoder = LabelEncoder()

df['FullTimeResult_enc'] = result_encoder.fit_transform(df['FullTimeResult'])



"""Change the date feature"""

df['MatchDate'] = pd.to_datetime(df['MatchDate'], errors='coerce')
df['MatchYear'] = df['MatchDate'].dt.year
df['MatchMonth'] = df['MatchDate'].dt.month
df['MatchDay'] = df['MatchDate'].dt.day
df.dropna(subset=['MatchYear'], inplace=True)





"""Train the Machine learning model"""

# ================= Features =================
# Exactly same structure as Flask input form
X = df[['HomeTeam_enc', 'AwayTeam_enc', 'MatchYear', 'MatchMonth', 'MatchDay',
        'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HY', 'AY', 'HR', 'AR']]

"""here i am selecting only the 16 featurs in X axis"""

y_class = df['FullTimeResult_enc']

"""in y axis i am selecting the full time result"""

from sklearn.model_selection import train_test_split

# ================= Train Models =================
X_train, X_test, y_train, y_test = train_test_split(X, y_class, test_size=0.2, random_state=42)

"""heer i am splite the train data and test data

train the model  for LogisticRegression
"""

from sklearn.linear_model import LogisticRegression

winner_model = LogisticRegression(max_iter=1000)
winner_model.fit(X_train, y_train)

"""Classification Model (Winner Model) – Accuracy + Confusion Matrix"""

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# ====== Predict on Test Set ======
y_pred = winner_model.predict(X_test)

# ====== Accuracy ======
accuracy = accuracy_score(y_test, y_pred)
print("Winner Model Accuracy:", accuracy)

"""accuracy of the model is 55.54%"""

# ====== Confusion Matrix ======
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", cm)

# ====== Classification Report ======
print("\nClassification Report:\n", classification_report(y_test, y_pred))





"""Train the model for Linear Regression"""

from sklearn.linear_model import LinearRegression

# Train regression models for predicting goals
y_home = df['FullTimeHomeGoals']
y_away = df['FullTimeAwayGoals']

home_goals_model = LinearRegression().fit(X, y_home)
away_goals_model = LinearRegression().fit(X, y_away)

home_goals_model = LinearRegression().fit(X, y_home)
away_goals_model = LinearRegression().fit(X, y_away)



"""Regression Models – RMSE, MAE, R² + Predictions"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# ====== Home Goals Evaluation ======
home_pred = home_goals_model.predict(X)
print("\nHome Goals Model:")
print("MAE:", mean_absolute_error(y_home, home_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_home, home_pred)))
print("R² Score:", r2_score(y_home, home_pred))

"""Mean Square errer = 89%

Root Mean Square Errer = 1.1

R2 Score is = 0.2
"""

# ====== Away Goals Evaluation ======
away_pred = away_goals_model.predict(X)
print("\nAway Goals Model:")
print("MAE:", mean_absolute_error(y_away, away_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_away, away_pred)))
print("R² Score:", r2_score(y_away, away_pred))

"""Away Prediction

Mean Square errer = 78%

Root Mean Square erre = 1

R2 Score is = 25%
"""

print("✅ Model training complete. Saved all .pkl files successfully!")



"""Save Model and make pkl file"""

import pickle, os

os.makedirs('models', exist_ok=True)

pickle.dump(winner_model, open('models/winner_model (1).pkl', 'wb'))

pickle.dump(home_goals_model, open('models/home_goals_model (1).pkl', 'wb'))

pickle.dump(away_goals_model, open('models/away_goals_model (1).pkl', 'wb'))

pickle.dump(team_encoder, open('models/team_encoder.pkl', 'wb'))

pickle.dump(result_encoder, open('models/result_encoder.pkl', 'wb'))

print("✅ Model training complete. Saved all .pkl files successfully!")





"""Summery of the Data And Model

This is epl_final Data set

In this dataset there are 9380 rows are ther

and 22 columns are ther

In this dataset 16 integer columns are there and 6 Object column are there

In this data set there are Not any null value and Duplicate are there

45.83% MATCH ARE WINNING THE HOME TEAM.
29.51% MATCH ARE WINNING THE AWAY TEAM.
24.66% MATCH ARE DROW

## coming to the model training

i am apply the two model here
1> logistic regression and

logistic regression midel accuracy is 55.54% and Precision is 0.51, and recall is 0.6, and f1 scoer is 0.56

2> linear regression

Home Goals Model:  

Mean square erre = 89%
Root Mean Square erre = 1.1
R2 Score is = 20

Away Goals Model:
Mean square erre = 78
Root Mean Square erre = 1
R2 Score is = 25
"""

